version: "3.8"

services:
  postgres:
    image: postgres:16
    restart: always
    expose:
      - "5432"
    volumes:
      - database-data2:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: 252525


  backend:
    build: ./
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    tty: true
    environment:
      PYTHONPATH: .
    depends_on:
      - "postgres"
    ports:
      - 8000:8000

volumes:
  database-data2: