"""First

Revision ID: 3b836d28601f
Revises: 
Create Date: 2024-06-27 00:07:50.359447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b836d28601f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_teams',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_roles'), nullable=False),
    sa.Column('password_reset_token', sa.String(length=64), nullable=True),
    sa.Column('password_reset_expire', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_users_email'), 'service_users', ['email'], unique=True)
    op.create_index(op.f('ix_service_users_username'), 'service_users', ['username'], unique=True)
    op.create_table('service_auth_tokens',
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_auth_tokens_secret'), 'service_auth_tokens', ['secret'], unique=True)
    op.create_table('user_team_association',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['service_teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['service_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'team_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_team_association')
    op.drop_index(op.f('ix_service_auth_tokens_secret'), table_name='service_auth_tokens')
    op.drop_table('service_auth_tokens')
    op.drop_index(op.f('ix_service_users_username'), table_name='service_users')
    op.drop_index(op.f('ix_service_users_email'), table_name='service_users')
    op.drop_table('service_users')
    op.drop_table('service_teams')
    # ### end Alembic commands ###
